# This is a basic workflow to help you get started with Actions

name: CI-workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm ci 

      - name : Build fortjs SDK
        run:  npm run buildpack
      
      - name: Install dependencies in benchmark
        run:  cd benchmarks && npm install
  dependency-check:
    name: Dependency-Check
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - name: Install dependencies
        run:   cd benchmarks && npm install
      - name: Download OWASP Dependency Check
        run: |
          VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
          curl -sL "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
          unzip dependency-check.zip
          
      - name: Restore cached Database
        uses: actions/cache/restore@v3
        with:
          path: ./dependency-check/data
          # Using datetime in cache key as OWASP database may change, without the pom changing
          key: ${{ runner.os }}-npm-${{ steps.get-date.outputs.datetime }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ steps.get-date.outputs.datetime }}
            ${{ runner.os }}-npm-
            
      - name: Run Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh --nvdApiKey "64fadad3-1b3e-4045-8507-10f176e7d057" --out report.html --scan .
      - name: Get Date
        id: get-date
        run: |
          echo "datetime=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: report.html
          
      - name: Cache Maven dependencies
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./dependency-check/data
          key: ${{ runner.os }}-npm-${{ steps.get-date.outputs.datetime }}-${{ hashFiles('**/package.json') }}
